config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#home'

  get '/signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  get '/auth/facebook/callback' => 'sessions#facebookcreate'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get '/user/most_destinations' => 'users#most_destinations', as: :most_destinations
  get '/destinations/five_star' => 'destinations#five_star', as: :five_star
  get '/cities/most_visited' => 'cities#most_visited', as: :most_visited
  get '/cities/highly_rated' => 'cities#highly_rated', as: :highly_rated

  resources :users do
    resources :destinations 
  end

  resources :cities, only: [:index, :show, :new, :create]
  resources :countries, only: [:index, :show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    has_many :destinations
    has_many :cities, through: :destinations
    validates :email, presence: true, uniqueness: true
    validates :name, presence: true
    scope :most_destinations, -> { joins(:destinations).group('destinations.user_id').order("count(destinations.user_id) desc").limit(1)}
    has_secure_password
  
    def last_destination
      self.destinations.last
    end
  
    def destination_count
      self.destinations.count
    end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
    
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name   
        user.image = auth.info.image 
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:index, :show]

    def index
        @users = User.all 
    end

    def show
        set_user
    end

    def most_destinations
        @user = User.most_destinations.first
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id 
            redirect_to user_path(@user), :flash => { :success => "Welcome, #{@user.name}! Your account has been successfully created." }
        else
            render :new 
        end
    end

    private 
    def user_params
        params.require(:user).permit(:email, :name, :password)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="list-details">
  <h4>Travelers</h4>
  <p><%= link_to "Who's Taken the Most Trips? Find Out Here!", most_destinations_url %></p>
  <% @users.each do |user| %>
    <div class="underlined-list">
      <span class="no-underline bold-text"><%= link_to user.name, user_destinations_path(user) %> </span><br>
      <% if user.destinations.count >= 1 %>
        <p>Last Destination Added: <%= user.last_destination.city.name %></p>
        <% else%>
        <p>No destinations added yet</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/most_destinations.html.erb
<div class="scope-page">
  <h3 class="blue-bold">Our most active traveler is <%= @user.name %>!</h3>
  <h4><%= @user.name %> has posted about <%= @user.destinations.count %> trips.</h4><br>
  <span class="blue-bold"><%= link_to "<-- Return to Travelers Page", users_path %></span>
</div>

app/views/users/most_trips.html.erb
<div class="scope-page">
  <h3 class="blue-bold">Our most active traveler is <%= @user.name %>!</h3>
  <h4><%= @user.name %> has posted about <%= @user.destinations.count %> trips.</h4><br>
  <span class="blue-bold"><%= link_to "<-- Return to Travelers Page", users_path %></span>
</div>

app/views/users/new.html.erb
<div class="start-pages signup-login">
  <h4 class="blue-bold">Sign Up for TripTracker!</h4><br>
    <%= form_for @user do |f| %>
      <%= f.text_field :email, placeholder: "Email", :size => 30 %>
      <%= f.text_field :name, placeholder: "Username", :size => 30 %>
      <%= f.password_field :password, placeholder: "Password", :size => 30 %><br><br>
      <%= f.submit "Create Account", :class => 'btn btn-block btn-success' %>
    <% end %>

    <div class="user-errors">
      <% if @user.errors.any? %>
        <div id="error_explanation">
            <p><%= pluralize(@user.errors.count, "error") %> prohibited this account from being created:</p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>

</div>

app/views/users/show.html.erb
<div class="info-box">
  <h4 class="box-heading"><%= @user.name %></h4>
  <% if @user.destinations.count == 0 %>
    <p>You haven't added any destinations yet.</p><br>
    <%= link_to "Explore Destinations", cities_path, :class => 'btn btn-sm btn-secondary btn-rounded' %>
  <% else %>
    <p>You've added <%= pluralize(@user.destination_count, "trip") %>.</p>
    <span class="bold-text">Last Trip Added:</span>
    <span class="no-underline"><%= link_to @user.last_destination.city.name, user_destination_path(@user, @user.last_destination) %></span><br><br>
    <%= link_to "View My 5-Star Trips", five_star_url %><br><br>
    <%= link_to "See All My Trips", user_destinations_path(@user), :class => 'btn btn-sm btn-secondary btn-rounded' %>
  <% end %>
    <%= link_to "Add New Destination", new_user_destination_url(@user), :class => 'btn btn-sm btn-info btn-rounded' %>
</div>