config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#home'

  get '/signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  get '/auth/facebook/callback' => 'sessions#facebookcreate'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get '/user/most_destinations' => 'users#most_destinations', as: :most_destinations
  get '/destinations/five_star' => 'destinations#five_star', as: :five_star
  get '/cities/most_visited' => 'cities#most_visited', as: :most_visited
  get '/cities/highly_rated' => 'cities#highly_rated', as: :highly_rated

  resources :users do
    resources :destinations 
  end

  resources :cities, only: [:index, :show, :new, :create]
  resources :countries, only: [:index, :show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :country
    has_many :destinations
    has_many :users, through: :destinations
    validates :name, presence: true, uniqueness: true
    validates :country_id, presence: true
    scope :most_visited, -> { joins(:destinations).group('destinations.city_id').order("count(destinations.city_id) desc").limit(1)}
    scope :highly_rated, -> { joins(:destinations).merge(Destination.group(:city_id).having('AVG(rating) >= 4.5'))}

  def city_plus_country
    "#{self.name}, #{country.name}"
  end

  def avg_rating
    if self.destinations.count == 0
      "This city hasn't been rated yet."
    else
      self.destinations.average(:rating).to_f.round(1)
    end
  end

  def country_name=(country_name)
    if country_name[:country] != ""
      country = Country.find_or_create_by(name: country_name[:country])
     self.country_id = country.id
    end
   end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    before_action :require_login
    
    def index
        @cities = City.all.order(:name)
    end

    def show
        @city = City.find(params[:id])
    end

    def most_visited
        @city = City.most_visited.first
    end

    def highly_rated
        @cities = City.highly_rated
    end

    def new
        @city = City.new
    end

    def create
        @city = City.create(city_params)
        if @city.save
            redirect_to cities_path, :flash => { :success => "You've added this city!" }
        else
            render :new
        end
    end

    private
    def city_params
        params.require(:city).permit(:name, :country_id, country_name:[:country])
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/highly_rated.html.erb
<div class="scope-page">
  <h3 class="blue-bold">Cities with Average Rating of 4.5 or Higher</h3>
  <% @cities.each do |c| %>
    <h4><%= "#{c.name} - #{c.avg_rating}" %></h4>
  <% end %>
  <br>
  <span class="blue-bold"><%= link_to "<-- Return to Cities Page", cities_path %></span>
</div>

app/views/cities/index.html.erb
<h4 class="align-table">Explore Cities</h4>
<span class="align-table"><%= link_to "Check Out the Most Reviewed City", most_visited_url %></span><br>
<span class="align-table"><%= link_to "View Our Highest Rated Cities", highly_rated_url %></span><br><br>
<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Average Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @cities.each do |city| %>
         <tr class="border-bottom">
            <td class="no-underline"><%= link_to city.city_plus_country, city_path(city) %></td>
            <td><%= city.avg_rating %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<br>

<div class="button-below-table">
  <%= link_to "Add New City", new_city_url, :class => 'btn btn-sm btn-primary btn-rounded' %>
</div>

app/views/cities/most_visited.html.erb
<div class="scope-page">
  <h3 class="blue-bold"><%= @city.city_plus_country %> is our most visited city!</h3>
  <h4>It has been visited <%= @city.destinations.count %> times by our travelers.</h4><br>
  <span class="blue-bold"><%= link_to "<-- Return to Cities Page", cities_path %></span>
</div>

app/views/cities/new.html.erb
<div class="form">
  <h3>Add New City</h3><br>

  <%= form_for @city do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>

    <%= f.label :country, "Select Country" %>
    <%= f.collection_select :country_id, Country.order('name ASC'), :id, :name, :include_blank => true %>

    <%= f.fields_for :country_name do |ctry_name| %>
      <%= f.label :country, "Or Add New Country" %>
      <%= ctry_name.text_field :country %><br><br>
      <% end %>

    <div class="form-errors">
      <% if @city.errors.any? %>
        <div id="error_explanation">
          <p><%= pluralize(@city.errors.count, "error") %> prohibited this city from being created:</p>
          <ul>
            <% @city.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <%= f.submit "Add City", :class => 'btn btn-sm btn-success' %>
  <% end %>
</div>

app/views/cities/show.html.erb
<div class="list-details">
  <h4><%= @city.city_plus_country %></h4>
  <span class="bold-text">Average Rating: </span><%= @city.avg_rating %><br>
  <p><span class="bold-text">Total Reviews: </span><%= @city.destinations.count %></p>

  <% @city.destinations.each do |destination| %>
    <div class="underlined-list">
      <%= destination.comment %>
      <p>- <%= destination.user.name %> (<%= destination.rating %> stars)</p>
    </div>
  <% end %>

  <% if !Destination.exists?(user_id: current_user.id, city_id: @city.id) %>
    <%= link_to "Been to #{@city.name}? Add it to your destinations!", new_user_destination_path(:user_id => current_user.id, :city_id => @city.id) %>
  <% end %>
</div>