config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#home'

  get '/signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  get '/auth/facebook/callback' => 'sessions#facebookcreate'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get '/user/most_destinations' => 'users#most_destinations', as: :most_destinations
  get '/destinations/five_star' => 'destinations#five_star', as: :five_star
  get '/cities/most_visited' => 'cities#most_visited', as: :most_visited
  get '/cities/highly_rated' => 'cities#highly_rated', as: :highly_rated

  resources :users do
    resources :destinations 
  end

  resources :cities, only: [:index, :show, :new, :create]
  resources :countries, only: [:index, :show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/destination.rb
class Destination < ApplicationRecord
    belongs_to :user
    belongs_to :city
    validates :city, presence: true
    validates_uniqueness_of :city_id, :scope => :user_id, message: "already added to your trips!"
    validates :rating, presence: true 
    validates_numericality_of :rating, :only_integer => true, message: "must be a whole number"
    validates_inclusion_of :rating, :in => 1..5, message: "must be between 1 and 5"
    validates :fave_attraction, presence: true 
    validates :comment, presence: true
    scope :five_star, -> { where(rating: 5) }

    def city_attributes=(attributes)
        if attributes[:city] != ""
          city = City.find_or_create_by(name: attributes[:city])
        if attributes[:country] != ""
          country = Country.find_or_create_by(name: attributes[:country])
        else
          country = Country.find_by(id: attributes[:country_id])
        end
        country.cities << city if city != "" && country != ""
        country.save if country != ""
        self.city_id = city.id
        end
      end
    
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    before_action :require_login

    def index
        find_user
        @destinations = @user.destinations.all 
    end

    def show
        find_user
        find_destination
    end

    def five_star
        set_user
    end

    def new
        set_user
        find_city
        @destination = Destination.new 
    end

    def create 
        set_user 
        find_destination
        @destination = @user.destinations.build(destination_params)
        if @destination.save
            redirect_to user_destinations_path(@user), :flash => { :success => "You've successfully added this trip." }
        else  
            render :new
        end
    end

    def edit
        set_user
        find_destination    
        if @destination.user != current_user
            redirect_to user_destinations_path(@user), :flash => { :error => "You are not allowed to edit another traveler's trip." }
        end
    end

    def update
        set_user
        find_destination
        if @destination.update(destination_params)
            redirect_to user_destinations_path(@user), :flash => { :success => "Your trip has been updated!" }
        else
            render :edit
        end
    end

    def destroy
        set_user
        find_destination
        @destination.destroy
        redirect_to user_destinations_path(@user), :flash => { :success => "Your trip has been deleted." }
    end

    private
    def find_user
        @user = User.find_by_id(params[:user_id])
    end

    def find_destination
        @destination = Destination.find_by_id(params[:id])
    end

    def find_city
        @city = City.find_by_id(params[:city_id])
    end

    def destination_params
        params.require(:destination).permit(:user_id, :city_id, :rating, :fave_attraction, :comment, city_attributes:[:city, :country, :country_id])
    end

end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= f. hidden_field :user_id, value: @user.id %>

<%= f.label :rating, "Rating (Scale of 1-5)" %>
<%= f.text_field :rating %><br><br>

<%= f.label :fave_attraction, "Must See Attraction" %>
<%= f.text_field :fave_attraction %><br><br>

<%=f.label :comment, "Share More Details" %><br><br>
<%= f.text_area :comment, :size => "35x5" %><br><br>

<div class="form-errors">
<% if @destination.errors.any? %>
  <div id="error_explanation">
    <p><%= pluralize(@destination.errors.count, "error") %> occurred:</p>
    <ul>
      <% @destination.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/destinations/edit.html.erb
<div class="form">
  <h3>Edit Trip</h3><br>
    <%= form_for :destination, url: user_destination_path, :method => 'patch' do |f| %>
      <%= f.hidden_field :city_id %>
      <%= f.label :city %>
      <%= f.text_field :city, value: @destination.city.name, readonly: true %><br><br>
      <%= render partial: 'form', locals: { f: f} %>
      <%= f.submit "Update Trip", :class => 'btn btn-sm btn-success auto' %>
    <% end %>
</div>

app/views/destinations/five_star.html.erb
<div class="scope-page">
  <h4 class="blue-bold">Destinations Rated 5 Stars by <%= @user.name %>:</h4><br>
  <% if @user.destinations.five_star.count >= 1 %>
    <% @user.destinations.five_star.each do |destination| %>
      <p class="no-underline"><%= link_to destination.city.city_plus_country, user_destination_path(@user, destination) %></p>
    <% end %>
    <% else %>
    <p>You don't have any 5-star destinations yet.</p>
  <% end %>
<span class="blue-bold"><%= link_to "<-- Return to Home Page", user_path(@user) %></span>

app/views/destinations/index.html.erb
<h4 class="align-table"><%= @user.name %>'s Destinations</h4>
<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Must See Attraction</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @destinations.each do |destination| %>
   
    <tr class="border-bottom">
      <td class="no-underline"><%= link_to destination.city.name, user_destination_path(@user, destination.id) %></td>
      <td><%= destination.fave_attraction %></td>
      <% if @user == current_user %>
        <td><%= link_to "Edit Destination", edit_user_destination_url(@user, destination), :method => 'get' %></td>
      <% else %>
        <td> </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="button-below-table">
  <% if @user == current_user %>
    <%= link_to "Add A New Destination", new_user_destination_url(@user), :class => 'btn btn-sm btn-primary btn-rounded' %>
  <% end %>
</div>

app/views/destinations/new.html.erb
<div class="form">
  <h3>Add New Destination</h3><br>
    <%= form_for :destination, url: user_destinations_path do |f| %>
      <% if @city %>
        <%= f.hidden_field :city_id, value: @city.id %>
        <%= f.label :city %>
        <%= f.text_field :city, value: @city.name, readonly: true %><br><br>
      <% else %>
        <%= f.label :city, "Select City" %>
        <%= f.collection_select :city_id, City.order('name ASC'), :id, :city_plus_country, :include_blank => true %><br>
        <p>* OR add a new city by entering details below:</p>
        <%= f.fields_for :city_attributes do |city_attr| %>
          <%= f.label :city, "City Name" %>
          <%= city_attr.text_field :city %>
          <%= f.label :country, "Select Country" %>
          <%= city_attr.collection_select :country_id, Country.order('name ASC'), :id, :name, :include_blank => true %>
          <%= f.label :country, "Add New Country" %>
          <%= city_attr.text_field :country %><br><br>
      <% end %>
    <% end %>

    <%= render partial: 'destinations/form', locals: { f: f } %>
    <%= f.submit "Add Destination" %>
    
  <% end %>
</div>

app/views/destinations/show.html.erb
<div class="info-box med-box">
  <h4 class="box-heading"><%= @user.name %>'s <%= @destination.city.name %> Trip!</h4>
  <p><span class="bold-text">Rating: </span><%= @destination.rating %></p>
  <p><span class="bold-text">Must See Attraction: </span><%= @destination.fave_attraction %></p>
  <p><span class="bold-text">Review: </span><%= @destination.comment %></p><br>


<% if @user == current_user %>
    <%= link_to "Edit Trip", edit_user_destination_url, :class => 'btn btn-sm btn-primary btn-rounded' %>
    <%= link_to "Delete Trip", user_destination_path, :method => 'delete', data: { confirm: "Are you sure?" }, :class => 'btn btn-sm btn-secondary btn-rounded' %>
  <% end %>