config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#home'

  get '/signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  get '/auth/facebook/callback' => 'sessions#facebookcreate'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get '/user/most_destinations' => 'users#most_destinations', as: :most_destinations
  get '/destinations/five_star' => 'destinations#five_star', as: :five_star
  get '/cities/most_visited' => 'cities#most_visited', as: :most_visited
  get '/cities/highly_rated' => 'cities#highly_rated', as: :highly_rated

  resources :users do
    resources :destinations 
  end

  resources :cities, only: [:index, :show, :new, :create]
  resources :countries, only: [:index, :show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
<% if !logged_in? %>
  <%= link_to("Log In", login_path) %>
  <%= link_to("Sign Up", signup_path) %>
<% else %>
  <%= link_to("Traveler", user_path(current_user), :class => 'logo') %>
  <%= link_to("My Trips", user_destinations_path(current_user)) %>
  <%= link_to("Cities", cities_path) %>
  <%= link_to("Countries", countries_path) %>
  <%= link_to("Travelers", users_path) %>
  <%= link_to("Log Out", logout_path) %>
<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traveler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

  </head>

  <body>

    <div class="topnav">
      <%= render '/layouts/header' %>
    </div>

    <% unless current_user %> 
        <%= link_to "Sign in with Facebook", '/auth/Facebook' %>
    <% else %>
        <%= current_user[:name] %>
        <%= link_to "Logout", logout_path, method: :delete %>
    <% end %>

    <%= yield %>
  </body>
</html>